version: 1.0.{build}
os: Visual Studio 2015
platform: x64
configuration:
- Debug
- Release
matrix:
  fast_finish: true
before_build:
- ps: >-
    if ($env:CONFIGURATION -eq "Debug") {
        utils/CSTYLE.ps1
    }
build:
  project: src/NVML.sln
  parallel: true
  verbosity: minimal
test_script:
- ps: >-
    if ($env:CONFIGURATION -eq "Debug") {
        cd src/test
        echo "`$NON_PMEM_FS_DIR = '\temp'" > testconfig.ps1
        echo "`$PMEM_FS_DIR = '\temp'" >> testconfig.ps1
        echo "`$PMEM_FS_DIR_FORCE_PMEM = 1" >> testconfig.ps1
        ./RUNTESTS.ps1 -b debug -o 60s -v
    }
