
name: Coverity

on:
  schedule:
    # run this job at 00:00 UTC every day
    - cron:  '0 0 * * *'

env:
  GITHUB_REPO: pmem/pmdk
  DOCKER_REPO: pmem/pmdk

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    env:
      COVERITY_SCAN_NOTIFICATION_EMAIL:  ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
      COVERITY_SCAN_TOKEN:               ${{ secrets.COVERITY_SCAN_TOKEN }}
      HOST_WORKDIR:   /home/runner/work/pmdk/pmdk
      WORKDIR:        utils/docker
      PMDK_CC:        gcc
      PMDK_CXX:       g++
      MAKE_PKG:       0
      REMOTE_TESTS:   1
      VALGRIND:       1
    strategy:
      matrix:
        CONFIG: ["COVERITY=1 OS=ubuntu OS_VER=19.10"]
    steps:
       - name: Print out the current date and time
         run: date

       - name: Clone the git repo
         uses: actions/checkout@v2

       - name: Pull or rebuild the image
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./pull-or-rebuild-image.sh

       - name: Run the build
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./build-CI.sh
