# Run tests of type 'long' (as defined in test frameworks).
#
# This workflow is run on 'self-hosted' runners.
name: PMEM long

on:
  workflow_dispatch:
  schedule:
    - cron:  '5 0 * * 6'    # At 00:05 on Saturday.

jobs:
  linux:
    name: PMEM_long
    if: github.repository == 'pmem/pmdk'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 960
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, rhel],[self-hosted, opensuse]]
        config: ['RUNTESTS.sh -t long -b debug',
                 'RUNTESTS.sh -t long -b nondebug',
                 'RUNTESTS.sh -t long -b static-debug',
                 'RUNTESTS.sh -t long -b static-nondebug',
                 'RUNTESTS.py -t long -b debug',
                 'RUNTESTS.py -t long -b nondebug',
                 'RUNTESTS.py -t long -b static_debug',
                 'RUNTESTS.py -t long -b static_nondebug']

    env:
      WORKDIR: utils/gha-runners

    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3

      - name: Get system information
        run: ./$WORKDIR/get-system-info.sh

      - name: Build
        run: ./$WORKDIR/build-pmdk.sh

      - name: Create testconfig file
        run: ./$WORKDIR/create-testconfig.sh

      - name: Run tests
        run: cd src/test/ && ./${{ matrix.config }}
