name: self_runner_setup

on:
  push:
  pull_request:
  schedule:
    - cron:  '0/5 * ? * *'    # At xx:05 .

jobs:
  linux:
    name: self_runner_setup
    if: github.repository == 'pmem/pmdk'
    runs-on: self-hosted, rockylinux, icx
    env:
      WORKDIR: utils/gha-runners

    steps:
        - name: List directory
          run: ls
