name: Valgrind bash

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 18 * * 5'    # At 18:00 on Friday.

jobs:
  linux:
    name: valgrind
    if: github.repository == 'osalyk/pmdk'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 4320 # wait max 3 days
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, Rocky8]]
        config: ['RUNTESTS -m force-enable',
                 'RUNTESTS -p force-enable',
                 'RUNTESTS -d force-enable',
                 'RUNTESTS -e force-enable']
    env:
      WORKDIR: utils/gha-runners

    steps:
        - name: Clone the git repo
          uses: actions/checkout@v3

        - name: Get system information
          run: ./$WORKDIR/get-system-info.sh

        - name: Build
          run: ./$WORKDIR/build-pmdk.sh

        - name: Create testconfig file
          run: ./$WORKDIR/create-testconfig.sh

        - name: Run tests
          run: cd src/test/ && ./${{ matrix.config }}
